
package org.example.entity;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.envers.Audited;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * CompanyMstr generated by hbm2java
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "company_mstr")
public class CompanyMstr extends BaseEntity implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "COMPANY_MSTR_SEQ", unique = true)
    private Long companyMstrSeq;
    @Column(name = "COMPANY_CD", length = 20)
    private String companyCd;
    @Column(name = "DISPLAY_NAME", length = 100)
    private String displayName;
    @Column(name = "LOGO_IMAGE", length = 100)
    private String logoImage;
    @Column(name = "CANDIDATE_LOGIN_LOGO_IMAGE_NAME", length = 100)
    private String candidateLoginLogoImageName;
    @Column(name = "BACKGROUND_IMAGE_NAME", length = 100)
    private String backgroundImageName;
    @Column(name = "BANNER_IMAGE_NAME", length = 100)
    private String bannerImageName;
    @Column(name = "MOBILE_LOGO_IMAGE_NAME", length = 100)
    private String mobileLogoImageName;
    @Column(name = "POINT_OF_CONTACT", length = 50)
    private String pointOfContact;
    @Column(name = "DOMAIN_NAME", length = 30)
    private String domainName;
    @Column(name = "DEFAULT_PASSWORD", length = 200)
    private String defaultPassword;
    @Column(name = "DEFAULT_COLOR_CODE", length = 200)
    private String defaultColorCode;
    @Column(name = "PANEL_COLOR_CODE", length = 200)
    private String panelColorCode;
    @Column(name = "LOGIN_WELCOME_TEXT", length = 200)
    private String loginWelcomeText;
    @Column(name = "HEADER_BACKGROUND_COLOR", length = 200)
    private String headerBackgroundColor;
    @Column(name = "LOGIN_BACKGROUND_POSITION", length = 200)
    private String loginBackgroundPosition;
    @Column(name = "LOGIN_DESKTOP_SIZE", length = 200)
    private String loginDesktopSize;
    @Column(name = "HEADER_LOGO", length = 200)
    private String headerLogo;
    @Column(name = "SETTING_ICON", length = 200)
    private String settingIcon;
    @Column(name = "SETTING_ICON_HOVER", length = 200)
    private String settingIconHover;
    @Column(name = "OAUTH_PROVIDER", length = 200)
    private String oauthProvider;
    @Column(name = "ENTITY_ID", length = 100)
    private String entityId;
}
