package org.example.entity;
// Generated 3 Aug, 2020 6:56:49 PM by Hibernate Tools 4.0.1.Final

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.envers.Audited;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;
import static org.hibernate.envers.RelationTargetAuditMode.NOT_AUDITED;

/**
 * DocumentKitFormLabels generated by hbm2java
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "document_kit_form_labels")
public class DocumentKitFormLabels extends BaseEntity implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DOCUMENT_KIT_LABEL_SEQ", unique = true, nullable = false)
	private Long documentKitLabelSeq;
	@Column(name = "DOCUMENT_KIT_SEQ")
	private Long documentKit;
	@Column(name = "FORM_LABEL_SEQ")
	private Long formLabels;
	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	private Long companyMstrSeq;
	@Column(name = "STEP_NUMBER")
	private Integer stepNumber;
	@Column(name = "VALIDATE_DOCUMENTS")
	private Boolean validateDocuments;
	@Column(name = "PRIORITY")
	private Integer priority;
}
