package org.example.entity;
// Generated 3 Aug, 2020 6:56:49 PM by Hibernate Tools 4.0.1.Final

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.envers.Audited;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;
import static org.hibernate.envers.RelationTargetAuditMode.NOT_AUDITED;

/**
 * DocumentKitFieldGroupsFieldMemberMap generated by hbm2java
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "document_kit_field_groups_field_member_map")
public class DocumentKitFieldGroupsFieldMemberMap extends BaseEntity implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DOCUMENT_KIT_FIELD_GROUP_FIELD_MEMBER_MAP_SEQ", unique = true, nullable = false)
	private Long documentKitFieldGroupFieldMemberMapSeq;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOCUMENT_KIT_FIELD_GROUP_SEQ", nullable = false)
	private DocumentKitFieldGroups documentKitFieldGroups;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FIELD_GROUP_CHILD_SEQ", nullable = true)
	private FieldGroupChild fieldGroupChild;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FIELD_GROUP_MEMBER_SEQ")
	private FieldGroupMembers fieldGroupMembers;
	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	private Long companyMstrSeq;
	@Column(name = "PREVIEW_SEQUENCE")
	private Integer previewSequence;
}
