package org.example.entity;
// Generated 22 Jun, 2020 5:01:42 PM by Hibernate Tools 4.0.1.Final

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.envers.Audited;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;
import static org.hibernate.envers.RelationTargetAuditMode.NOT_AUDITED;

/**
 * FieldGroupMembers generated by hbm2java
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "field_group_child")
@Audited(targetAuditMode = NOT_AUDITED)
public class FieldGroupChild extends BaseEntity implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "FIELD_GROUP_CHILD_SEQ", unique = true, nullable = false)
	private Long fieldGroupChildSeq;
	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	private Long companyMstrSeq;
	@Column(name="PARENT_FIELD_GROUP_CHILD_SEQ")
	private Long parentFieldGroupChildSeq;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOCUMENT_KIT_FIELD_GROUP_SEQ", nullable = false)
	private DocumentKitFieldGroups documentKitFieldGroups;
	@Column(name="FIELD_GROUP_CLASSNAME")
	private String fieldGroupClassName;
	@Column(name="INTERNAL_GROUP_CD")
	private String internalGroupCd;
	@Column(name = "HIDE")
	private boolean hide;
	@Column(name = "PRIORITY")
	private Integer priority;

}
