package org.example.entity;// default package
// Generated 18 Jun, 2020 3:27:19 PM by Hibernate Tools 4.0.1.Final

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.envers.Audited;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;
import static org.hibernate.envers.RelationTargetAuditMode.NOT_AUDITED;

/**
 * FieldMemberPersistMstr generated by hbm2java
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "field_member_persist_mstr")
public class FieldMemberPersistMstr extends BaseEntity implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "FIELD_MEMBER_PERSIST_SEQ", unique = true, nullable = false)
	private Long fieldMemberPersistSeq;
	@Column(name = "FIELD_GROUP_MEMBER_SEQ")
	private Long fieldGroupMembers;
	@Column(name = "COMPANY_MSTR_SEQ")
	private Long companyMstrSeq;
	@Column(name = "TABLE_NAME", length = 200)
	private String tableName;
	@Column(name = "COLUMN_NAME", length = 200)
	private String columnName;
	@Column(name = "VARIABLE_NAME", length = 200)
	private String variableName;
	@Column(name = "API_KEY", length = 200)
	private String apiKey;

}
