package org.example.entity;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * RequestStatusMstr generated by hbm2java
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "request_status_mstr")
public class RequestStatusMstr extends BaseEntity implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "REQUEST_STATUS_MSTR_SEQ", unique = true, nullable = false)
	private Long requestStatusMstrSeq;
	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	private Long companyMstrSeq;
	@Column(name = "REQUEST_TYPE")
	private String requestType;
	@Column(name = "REQUEST_CD")
	private String requestCd;
	@Column(name = "PRIORITY")
	private Integer priority;

}
