package org.example.entity;
// Generated 22 Jun, 2020 5:01:42 PM by Hibernate Tools 4.0.1.Final

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.envers.Audited;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;
import static org.hibernate.envers.RelationTargetAuditMode.NOT_AUDITED;

/**
 * ValidatorsMstr generated by hbm2java
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "validators_mstr", uniqueConstraints = @UniqueConstraint(columnNames = "VALIDATION"))
public class ValidatorsMstr extends BaseEntity implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "VALIDATOR_MSTR_SEQ", unique = true, nullable = false)
	private Long validatorMstrSeq;
	@Column(name = "COMPANY_MSTR_SEQ")
	private Long companyMstrSeq;
	@Column(name = "VALIDATION", unique = true)
	private String validation;
	@Column(name = "MESSAGE")
	private String message;


}
